version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_application
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql